### ISSUE TITLE
Blocks do not change to dark background in dark mode and make text unreadable

### ISSUE THREAD

**Issue by M-arcus** [shopware/design-portal#177]
See here: https://shopware.design/product-experience/content/basics.html

Light:

![image](https://github.com/shopware/design-portal/assets/25648755/8955598a-460b-46c8-805f-dfa8e0b38d70)

Dark:

![image](https://github.com/shopware/design-portal/assets/25648755/f0133300-dc47-404a-a5c7-5fe51eb96b9c)

**Comment by bojanrajh** [comment]
@Weltraumakustik Along with fixing this, there's also issue with the `::: info` note and [custom](https://github.com/shopware/design-portal/blob/d0bfc402aa1b20e1f366bd2aebf282934e41dbdb/.vitepress/theme/custom.css#L24) style visible on the screenshot. We probably want to review that and move some of it to the theme repo.
